name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.4'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check Linting
        run: npm run lint

      - name: Check tests
        run: npm run test:coverage

      - name: Run Coveralls
        uses: coverallsapp/github-action@v2

      - name: Deploy to Staging
        run: echo "Implantação no ambiente de pré-produção"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "Implantação no ambiente de produção"

